### ISSUE TITLE
Deprecation of dynamic properties

### ISSUE THREAD

**Issue by stollr** [zbateson/stream-decorators#14]
Using this library with PHP 8.2 leads to a deprecation message.

> Creation of dynamic property ZBateson\StreamDecorators\NonClosingStream::$stream is deprecated
> Stack trace:
> #0 vendor/guzzlehttp/psr7/src/StreamDecoratorTrait.php(21): Symfony\Bridge\PhpUnit\DeprecationErrorHandler->handleError(8192, '...', '...', 21)
> #1 vendor/zbateson/mail-mime-parser/src/Stream/StreamFactory.php(90): ZBateson\StreamDecorators\NonClosingStream->__construct(Object(GuzzleHttp\Psr7\Stream))
> #2 vendor/zbateson/mail-mime-parser/src/Stream/StreamFactory.php(75): ZBateson\MailMimeParser\Stream\StreamFactory->newNonClosingStream(Object(GuzzleHttp\Psr7\Stream))
> #3 vendor/zbateson/mail-mime-parser/src/Stream/StreamFactory.php(55): ZBateson\MailMimeParser\Stream\StreamFactory->newLimitStream(Object(GuzzleHttp\Psr7\Stream), 70, 2117)
> #4 vendor/zbateson/mail-mime-parser/src/Parser/Part/ParserPartStreamContainer.php(83): ZBateson\MailMimeParser\Stream\StreamFactory->getLimitedContentStream(Object(ZBateson\MailMimeParser\Parser\Proxy\ParserMessageProxy))
> #5 vendor/zbateson/mail-mime-parser/src/Parser/Part/ParserPartStreamContainer.php(109): ZBateson\MailMimeParser\Parser\Part\ParserPartStreamContainer->requestParsedContentStream()
> #6 vendor/zbateson/mail-mime-parser/src/Message/MessagePart.php(99): ZBateson\MailMimeParser\Parser\Part\ParserPartStreamContainer->hasContent()
> #7 vendor/zbateson/mail-mime-parser/src/Message/MessagePart.php(116): ZBateson\MailMimeParser\Message\MessagePart->hasContent()
> #8 vendor/zbateson/mail-mime-parser/src/Message/MessagePart.php(166): ZBateson\MailMimeParser\Message\MessagePart->getContentStream('...')
> #9 vendor/zbateson/mail-mime-parser/src/Message.php(148): ZBateson\MailMimeParser\Message\MessagePart->getContent('...')
> #10 src/Service/EmailParsing/Parsers/CarelPlantWatchProParser.php(35): ZBateson\MailMimeParser\Message->getTextContent()

The `StreamDecoratorTrait` tries to access `$this->stream` although it is not declared in the `NonClosingStream` for example..

**Comment by phpfui** [comment]
I believe this has been fixed in https://github.com/zbateson/stream-decorators/pull/10 and can be closed.
